pub fn get_options() -> Vec<String> { "meter, meters, metre, metres, second, seconds, secs, sec, gram, grams, kilogram, kilograms, ampere, amperes, kelvin, candela, candelas, exa, peta, tera, giga, mega, kilo, hecto, deca, deci, centi, milli, micro, nano, pico, ton, kibi, mebi, gibi, tebi, pebi, exbi, minute, minutes, hour, hours, hr, hrs, day, days, week, weeks, year, years, decade, decades, century, centuries, byte, bytes, octet, bit, bits, newton, newtons, pascal, pascals, joule, joules, british_thermal_units, british_thermal_unit, btu, btus, cal, calorie, kcal, watt, watts, horsepower, coulomb, volt, volts, ohm, ohms, siemens, sievert, gray, farad, weber, hertz, hz, bar, bars, litre, liter, liters, litres, atomic_mass_unit, u, amu, planck, placks_constant, electron_volt, eV, elementary_charge, lumen, lumens, lux, astronomical_unit, astronomical_units, au, gravity, gravity_constant, atm, atmosphere, atmospheric_pressure, mach, room_temperature, standard_temperature, degree, degrees, micron, microns, circle, circles, pi, golden_ratio, e, inf, lightspeed, light, speedoflight, speed_of_light, percent, %, percents, ppm, partspermillion, ppb, partsperbillion, ppt, partspertrillion, karat, inch, inches, foot, feet, yard, yards, mile, miles, cup, cups, tablespoon, tbl, tbsp, tblsp, teaspoon, tsp, pound, pounds, lb, lbs, grain, grains, ounce, ounces, oz, gallon_UK, gallon_US, knot, knots,
add_one, root, nth_root, n_root, log, sqrt, square_root, 2root, root2, sin, sine, cos, cosine, tan, tangent, arcsine, arcsin, asin, asine, arccosine, arccos, arcos, acos, acosine, arctan, arctangent, atan, atangent, ln, natural_log, natural_ln, log_natural, lg, log10, log_base_10, log_base_ten, log2, 2log, log_base_2, log_base_two, exp, round_down, floor, rdown, roundd, round_up, ceil, rup, roundu, ceiling, round, abs, absolute, absol, absolutes, to, in, convert, convert_to, ans, last, answer, last_answer, clip, copy, clipboard
PRECISION:, help, exit, quit, clear, OUTPUT_ONLY:,
eq, equal, is_equal, is_equal_to, equal_to, gt, greater, greater_than, lt, less, less_than,
c_to_k, celsius_to_kelvin, celsius, units, get_units, unit
"
        .split(&[' ', ',', '\n'])
        .into_iter()
        .map(|v| {v.to_string()})
        .collect()
}
